name: CI
on: [push]

jobs:
  unit-test:
    name: Unit testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install composer dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.1

      - name: Run unit tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.6
          php_version: 8.1
          php_extensions: "xdebug"
          args: "-d date.timezone=UTC"
          configuration: phpunit.xml
          testsuite: AllValidatorsTests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}